branch-defaults:
  master:
    environment: SmartLock-env
environment-defaults:
  SmartLock-env:
    branch: null
    repository: null
global:
  application_name: Smart Lock
  default_ec2_keyname: ec2-ubuntu
  default_platform: arn:aws:elasticbeanstalk:ap-south-1::platform/Python 3.6 running
    on 64bit Amazon Linux/2.9.5
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
